# Generated by Django 5.1.6 on 2025-04-14 03:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porto', '0002_project_delete_certification_delete_tag_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('category', models.OneToOneField(db_column='category_slug', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='porto.skillcategory', to_field='slug')),
                ('color', models.CharField(help_text="Tailwind base color, e.g., 'blue'", max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='skill',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='porto.skill'),
        ),
    ]
