# Generated by Django 5.1.6 on 2025-04-15 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porto', '0003_color_project_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(null=True, upload_to='static/img'),
        ),
    ]
