# Generated by Django 5.1.6 on 2025-04-15 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porto', '0004_project_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='skill',
        ),
        migrations.AddField(
            model_name='project',
            name='skill',
            field=models.ManyToManyField(related_name='projects', to='porto.skill'),
        ),
    ]
